### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by EndruK** [errollw/smartboards2#4]
Hi,
I want to set up this project. Can you please give me a short guide how to configure the project that it runs? It seems that configuration files are missing.
Thanks for any help :)

Greeting André

**Comment by errollw** [comment]
Can you be a bit more specific about which files you think are missing? What sort of error is being thrown?

**Comment by Stechpalme** [comment]
Hi errolw,
I solved the problem:
I simply forgot to change the permissions so that apache was not able to access or create any necessary files.

**Comment by errollw** [comment]
Okay, great! Please get in touch if you have any questions or issues, I'd
love to know how you guys use the system.
